name: "Create PR"

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Generate GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ env.OWNER }} # 操作したいリポジトリのオーナーを指定する
      - run: mkdir ./downloaded-pages-content
      - name: Download GitHub Pages Artifact
        uses: actions/download-artifact@v4
        with:
          path: './downloaded-pages-content' # ダウンロード先のディレクトリ
      - name: Download Dir
        run: |
          ls -R
      - name: Clone private repository
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          # クローンするプライベートリポジトリ名に応じて <REPO_NAME> を書き換える
          git clone https://x-access-token:"$GITHUB_TOKEN"@github.com/chinnosuke/privateTest.git
          ls -R
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x
      - run: |
           dotnet run --project ./Main
           mkdir data
           mv test.csv ./data
           echo "<h1>Hello GitHub Pages!</h1>" > data/index.html 
      - uses: actions/upload-artifact@v4
        with:
          name: my_site
          path: data
      - uses: actions/upload-pages-artifact@v3
        with:
          path: data
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment